### ISSUE TITLE
Header sizes look huge when editing

### ISSUE THREAD

**Issue by kiriappeee** [insanum/obsidian_gruvbox#22]
Example when editing

![image](https://user-images.githubusercontent.com/208123/156492153-6240d73e-8820-4855-b97b-ffdaae4e9bec.png)

Example in reading mode

![image](https://user-images.githubusercontent.com/208123/156492176-a6313ad1-289d-4f0c-817b-400fe48855cb.png)

The reading mode works as expected. The editing mode is broken regardless of whether I'm in live preview or not.

The bug appeared yesterday (I missed whether there was a software update or not) 

I'm on Obsidian version 0.13.28.

No CSS snippets/custom css installed. Used a fresh install of the gruvbox theme. Font size is 16.

Let me know if I can provide more details to try and track this one down. Really appreciate the work you've done on the theme.

**Comment by kiriappeee** [comment]
I checked on the discord, and was pointed to this note from `v0.13.27` 

> Developers
>- Theme developers: you can also now use variables for heading font sizes with --h1, --h2, etc. We've also moved heading font sizes from cm-header-x to HyperMD-header-x to avoid certain elements not being properly up-sized like LaTeX and inline code.

For the moment, I've broken out the header styling into `cm-header` and `cm-header x` seperately.

This is my quick and dirty fix.

```css
.cm-header {
    font-size: 1.3em !important;
    font-weight: 500 !important;
}

.cm-header-1
{
    color: var(--text-title-h1) !important;
}


.cm-header-2
{
    color: var(--text-title-h2) !important;
}

.cm-header-3
{
    color: var(--text-title-h3) !important;
}

.cm-header-4
{
    color: var(--text-title-h4) !important;
}

.cm-header-5
{
    color: var(--text-title-h5) !important;
}

.cm-header-6
{
    color: var(--text-title-h6) !important;
}
```
