### ISSUE TITLE
Mermaid sequence diagram sequence numbers unreadable

### ISSUE THREAD

**Issue by ashemedai** [insanum/obsidian_gruvbox#27]
When using mermaid sequence diagrams in Obsidian with this theme, the numbers used when using [sequence numbers](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers) are unreadable.

Example:

![image](https://user-images.githubusercontent.com/610865/167814780-ed5e7329-fd49-4d5e-bd1e-f92b2bd1be41.png)

It seems that this can be styled using something like the following (used `neutral-orange` as a test):

```css
.mermaid .sequenceNumber                                                                                                                                                                                                                                                          {
    filter: invert(42%) sepia(46%) saturate(5880%) hue-rotate(11deg) brightness(97%) contrast(89%);
}
```

The `filter` was calculated via this [Codepen](https://codepen.io/sosuke/pen/Pjoqqp), found via this [SO question](https://stackoverflow.com/questions/22252472/how-to-change-the-color-of-an-svg-element). There might be better ways to do this and use the colour variables, but this is far outside my expertise.

But it works:

![image](https://user-images.githubusercontent.com/610865/167817043-0f13aafa-0514-439a-ad65-909403a809ba.png)

The colour `neutral-green` also works fairly well:

```css
filter: invert(51%) sepia(84%) saturate(405%) hue-rotate(21deg) brightness(94%) contrast(91%);
```

![image](https://user-images.githubusercontent.com/610865/167817688-a34a8e1f-cfdc-4033-8777-55fa8e919939.png)

Alternatively, styling the `messageLine0` and leaving the `sequenceNumber` alone will yield something like this:

```css
.mermaid .messageLine0
{
    filter: invert(51%) sepia(84%) saturate(405%) hue-rotate(21deg) brightness(94%) contrast(91%);
}
```

![image](https://user-images.githubusercontent.com/610865/167821778-4a1b98b2-b787-4ce5-901f-a9835315355d.png)

Do note that there's at least also a `messageLine1`
